

insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Business Development', '2017-10-04 15:06:55');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Engineering', '2020-01-08 12:28:01');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Services', '2019-02-16 21:14:26');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Research and Development', '2015-02-10 12:20:54');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Support', '2016-09-27 10:22:49');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Sales', '2016-04-30 10:38:09');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Marketing', '2014-10-30 00:53:08');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Training', '2009-04-18 22:57:11');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Human Resources', '2012-07-30 15:13:17');
insert into DEPARTMENT (name, LAST_UPDATE_TIMESTAMP) values ('Legal', '2004-07-27 14:09:14');


insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-14 17:29:36', 'Claresta', 'Jenyns', 'Female', 'The Boss', '2006-09-13', null, 6, null);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-23 19:47:06', 'Sukey', 'Maddinon', 'Female', 'Executive Secretary', '2000-03-03', null, 7, 1);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-12-14 15:42:17', 'Almeda', 'Levecque', 'Female', 'Financial Analyst', '2014-06-05', null, 10, 1);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-01-17 10:17:48', 'Trev', 'Brill', 'Male', 'Geological Engineer', '2004-04-04', null, 2, 1);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-12 00:59:59', 'Robbert', 'Tutchell', 'Male', 'Research Nurse', '2013-06-26', null, 4, 2);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-10-22 04:55:41', 'Joete', 'Capozzi', 'Male', 'Data Coordinator', '2013-08-25', null, 8, 2);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-12-06 06:11:38', 'Dame', 'Caff', 'Male', 'Health Coach IV', '2006-07-31', null, 9, 2);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-06 00:39:50', 'Franzen', 'Galia', 'Male', 'Associate Professor', '2019-05-06', null, 10, 2);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-08-18 15:36:37', 'Vincenty', 'Pottery', 'Male', 'Statistician III', '2016-04-15', null, 3, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-10-10 02:02:47', 'Andra', 'Richfield', 'Female', 'Research Nurse', '2017-04-08', null, 9, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-03 09:51:54', 'Erasmus', 'Illsley', 'Male', 'Quality Engineer', '2002-12-13', null, 6, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-12-23 01:01:45', 'Betti', 'O''Flannery', 'Female', 'Statistician III', '2005-08-15', null, 8, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-05-12 21:37:19', 'Peyter', 'Clail', 'Male', 'Financial Analyst', '2009-01-04', null, 2, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-12-03 16:54:34', 'Rhody', 'Margery', 'Female', 'Nurse', '2003-10-08', null, 2, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-06-26 03:24:47', 'Heda', 'Crone', 'Female', 'Software Engineer II', '2017-07-22', null, 9, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-04-01 05:09:53', 'Lissa', 'Stonner', 'Female', 'Technical Writer', '2016-11-14', null, 6, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-01-25 18:15:34', 'Urbanus', 'Keers', 'Male', 'VP Product Management', '2017-07-08', null, 2, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-01-07 23:38:08', 'Kiersten', 'Havercroft', 'Male', 'Design Engineer', '2002-06-06', null, 4, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-05-01 05:38:13', 'Farris', 'Lindsay', 'Male', 'Accounting Assistant IV', '2004-10-23', null, 7, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-10-05 23:31:54', 'Maxine', 'Yoxall', 'Female', 'Recruiting Manager', '2021-09-18', null, 10, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-10-16 07:37:00', 'Mandel', 'Coda', 'Male', 'Help Desk Operator', '2003-09-06', null, 5, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-11-13 19:15:45', 'Reggis', 'Coulthard', 'Male', 'Recruiter', '2009-06-25', '2013-07-15', 1, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-05-20 21:27:42', 'Evangelina', 'Aimer', 'Female', 'Human Resources Assistant I', '2014-12-18', null, 8, 3);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-03-15 19:41:19', 'Iago', 'Eakeley', 'Male', 'Help Desk Technician', '2020-03-21', null, 5, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-04-06 01:08:04', 'Garland', 'Aymer', 'Female', 'Data Coordinator', '2018-05-16', null, 9, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-04-04 22:38:29', 'Tierney', 'Kemet', 'Female', 'Chemical Engineer', '2014-04-11', null, 6, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-03-29 08:14:45', 'Idell', 'Bernholt', 'Female', 'Geologist III', '2020-07-16', null, 2, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-04-21 12:54:54', 'Pall', 'Mulvany', 'Male', 'Biostatistician IV', '2014-08-26', null, 2, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-04-17 06:35:31', 'Dex', 'Lightwing', 'Male', 'Nurse', '2002-10-03', null, 3, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-07-28 10:00:49', 'Leanora', 'Carthew', 'Female', 'Automation Specialist III', '2023-01-21', null, 5, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-10 07:38:04', 'Izzy', 'Rising', 'Male', 'Media Manager IV', '2004-12-26', null, 1, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-06-08 00:01:07', 'Corbet', 'Casperri', 'Male', 'VP Sales', '2006-06-02', null, 6, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-11-06 01:58:51', 'Giraldo', 'Dyshart', 'Male', 'Research Assistant III', '2020-08-30', null, 7, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-08-08 16:26:33', 'Glad', 'Pechell', 'Female', 'VP Quality Control', '2017-09-17', null, 8, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-07-31 01:34:35', 'Elita', 'Newhouse', 'Female', 'Analog Circuit Design manager', '2013-04-19', null, 7, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-09-03 11:52:40', 'Sherill', 'Downgate', 'Female', 'Senior Financial Analyst', '2012-12-01', null, 7, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-17 12:14:15', 'Ogden', 'Ivatt', 'Male', 'Executive Secretary', '2010-03-06', null, 3, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-01-18 16:01:17', 'Kleon', 'Brands', 'Male', 'Pharmacist', '2004-01-31', null, 7, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-01 17:25:08', 'Karlotte', 'Basset', 'Male', 'GIS Technical Architect', '2013-10-11', '2032-04-05', 5, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-05-17 05:33:00', 'Cleveland', 'Rollings', 'Male', 'Quality Control Specialist', '2015-12-13', null, 2, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-02-21 20:17:04', 'Chiarra', 'Wherrit', 'Female', 'Web Designer I', '2017-05-19', '2007-04-05', 2, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-12-06 05:22:32', 'Craggie', 'Biglin', 'Male', 'Engineer III', '2002-10-13', null, 2, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-11-18 23:49:57', 'Monti', 'Frossell', 'Male', 'Electrical Engineer', '2016-11-22', null, 3, 10);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-09-08 13:13:14', 'Karole', 'Duker', 'Female', 'VP Quality Control', '2006-11-02', null, 7, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-09-21 07:15:51', 'Giffard', 'Sinton', 'Male', 'Associate Professor', '2009-09-17', null, 1, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-01-04 14:57:21', 'Alwin', 'Ghilardini', 'Male', 'Web Designer II', '2013-09-21', null, 10, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-08-12 02:47:26', 'Fritz', 'Wapplington', 'Male', 'Web Developer IV', '2005-09-12', null, 10, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2023-03-27 14:46:15', 'Ely', 'Alforde', 'Male', 'Programmer III', '2012-04-01', null, 6, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-07-12 05:09:29', 'Jody', 'Jandourek', 'Male', 'Administrative Officer', '2003-06-07', null, 7, 36);
insert into EMPLOYEE (LAST_UPDATE_TIMESTAMP, FIRSTNAME, LASTNAME, GENDER, JOB_TITLE, CONTRACT_STARTDATE, CONTRACT_ENDDATE, DEPARTMENT_ID, MANAGER_ID) values ('2022-10-25 17:48:36', 'Sherri', 'Kedwell', 'Male', 'Software Test Engineer II', '2019-11-23', null, 8, 36);


insert into USERS (LOGIN, PASSWD, BIRTH_DATE, ENABLED) values ('reader', 'reader','1981-12-27',TRUE);
insert into USERS (LOGIN, PASSWD, BIRTH_DATE, ENABLED) values ('writer', 'writer','1988-01-13',TRUE);
insert into USERS (LOGIN, PASSWD, BIRTH_DATE, ENABLED) values ('minor', 'minor','2015-09-12',TRUE);
insert into USERS (LOGIN, PASSWD, BIRTH_DATE, ENABLED) values ('disabled', 'disabled','2000-02-05',FALSE);

insert into USER_PERMISSION(USER_LOGIN,PERMISSION) values ('writer','CAN_WRITE');
insert into USER_PERMISSION(USER_LOGIN,PERMISSION) values ('minor','CAN_WRITE');
commit;


